### PR TITLE
fix: Set project as workspace folder

### LINKED ISSUE #1155: [regression] Create template codelens no longer works
When clicking on the create template codelens, nothing happens:

Screenshot 2023-09-11 at 16 29 55

The Qute server logs show

```
[Trace - 04:27:38 PM] Sending request 'workspace/executeCommand - (21)'.
Params: {
  "command": "qute.command.generate.template.content",
  "arguments": [
    {
      "projectUri": "kusquar",
      "templateFileUri": "file:/Users/fbricon/Dev/kusquar/src/main/resources/templates/paged.html",
      "templateFilePath": "src/main/resources/templates/paged.html",
      "parameters": []
    }
  ]
}


[Trace - 04:27:38 PM] Received response 'workspace/executeCommand - (21)' in 1ms.
No result returned.
Error: {
  "code": -32001,
  "message": "Cannot findproject with the uri \u0027kusquar\u0027.",
  "data": {
    "message": "Cannot findproject with the uri \u0027kusquar\u0027."
  }
}
```

### PR DESCRIPTION
**Pull request by angelozerr**
fix: Set project as workspace folder

Fixes #1155

### CODE REVIEW

**Comment by fbricon** [comment]
looks like the LS don't start anymore

**Comment by angelozerr** [comment]
> looks like the LS don't start anymore

which project are you testing?

**Comment by fbricon** [comment]
> > looks like the LS don't start anymore
> 
> which project are you testing?

Some project that didn't work on the main branch either. Except for the known multimodule issues with Qute projects, this PR looks fine, so I'm OK to merge

**Comment by angelozerr** [comment]
This PR avoidd using file system watcher on ls side which blocks the ls when templates folder doesn't exist.

But we need to implement lsp watcher files because I think we will loose some features like if you have a template A which includes B with #include and you delete B without opening  it it should retrigger validation and remove from cache the B template. 

I need to test this feature.

**Comment by fbricon** [comment]
so if you have a page.html with an include like 
```
{#include include/somepage}

{/}
```

Now if you delete the `include/` folder, no error shows at the include definition, unless you make a change to the page.

**Comment by fbricon** [comment]
Similarly, if you have a so if you have a page.html with an include like 
```
{#include include/somepage}

{/}
```
and  the `include/` folder doesn't exist, an error is shown at `include/somepage`, but if you ctrl+click on it, generate the missing template, the error doesn't go away

**Comment by fbricon** [comment]
Thanks @angelozerr!

**Pull request merged**
