### PR TITLE
Automate basic UI test that creates new Quarkus project and builds it using gradle (+ update for UI changes in 2020.2 IntelliJ)

### LINKED ISSUE #217: Automate basic UI test that creates new Quarkus project and builds it using gradle

### LINKED ISSUE #305: Review UI changes in the newest IntelliJ Idea (2020.2) and update the UI tests

### PR DESCRIPTION
**Pull request by zcervink**
Add new automated test and updates for changes in UI:
- Fixes #217
- Fixes #305

Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>

Please review @jrichter1 @jeffmaury

### CODE REVIEW

**Comment by zcervink** [comment]
@jeffmaury @jrichter1 Please review. _Rebase_ was inevitable to cope with the 'Close Project' issue on Windows and Linux.

**Comment by jeffmaury** [comment]
I think this one should be merged into #310 to make sure the IT are ok

**Comment by zcervink** [comment]
@jeffmaury I have fixed the issue in the https://github.com/redhat-developer/intellij-quarkus/pull/310, now all checks are green. After we merge #310, I will rebase this PR + fix the conflicts (I think there will be at least one conflict). After that we will see results of IT.

**Comment by jeffmaury** [comment]
I don't get it because #310 is still broken so there is no chance it will be merged

**Comment by zcervink** [comment]
Please review @jeffmaury @jrichter1 This PR is ready for review as well as https://github.com/redhat-developer/intellij-quarkus/pull/310 (which is already approved by @jrichter1). Both PRs cannot be merged at once, there are conflicts between them that need to be resolved manually.

**Review by jeffmaury — APPROVED** [review]
Approving although I don't understand the rationale for computing ideaVersion as I don't see it being used then

**Comment by zcervink** [comment]
> Approving although I don't understand the rationale for computing ideaVersion as I don't see it being used then

I am planning to use it very soon. I am going to update the UI tests to support the newest IntelliJ version and keep the support for older version (if implemented). I will discuss that more further with @jrichter1. I do not want to block this PR any longer, I will do that very soon in separate PR.

**Comment by jrichter1** [comment]
I was under the impression that #310 was supposed to be the first step. Why try to push two separate PRs now, when it's clear there will be conflicts?

To make things simple:
 - make sure #310 is merged
 - rebase this PR
 - then we can review this

**Comment by zcervink** [comment]
@jeffmaury I have rebased the PR, after your approval from last I think we can merge.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
