### PR TITLE
Rename of the titles and branch names of automatically generated PRs for updating the Quarkus runtime version.

### LINKED ISSUE #313: Automatically generated PRs to update the version of Quarkus runtime should have more understandable titles and branch names
According to some people who do not work on the project as developers/testers, the title such as **Switch Quarkus runtime to 1.10.1.Final** is too short and confusing, the people do not know what the PRs do.
- example PR - https://github.com/redhat-developer/intellij-quarkus/pull/307

### PR DESCRIPTION
**Pull request by zcervink**
Fixes #313

Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>

@jeffmaury please review and we can discuss together with @vkuznyetsov

### CODE REVIEW

**Comment by zcervink** [comment]
@jrichter1 maybe you can add your opinion too.

**Review by jeffmaury — APPROVED** [review]

**Comment by zcervink** [comment]
@jeffmaury I have talked to @vkuznyetsov yesterday, he has approved this PR. You can merge, there is nothing to do more to this issue.

**Comment by jeffmaury** [comment]
Can't be merged this is a draft pr

**Comment by zcervink** [comment]
@jeffmaury sorry, now it can be merged.

**Pull request merged**
