### PR TITLE
fix: Deadlock with IDEA EAP 2023-3 EAP

### LINKED ISSUE #1192: Deadlock with IDEA EAP 2023-3 EAP
IJ eventually totally freezes at some point

```


Found one Java-level deadlock:
=============================
"AWT-EventQueue-0":
  waiting to lock monitor 0x0000600004efc1a0 (object 0x0000000788e5bb80, a java.util.HashMap),
  which is held by "JobScheduler FJ pool 12/11"

"JobScheduler FJ pool 12/11":
  waiting to lock monitor 0x0000600004ed8000 (object 0x000000079ecd8c60, a java.util.LinkedHashMap),
  which is held by "JobScheduler FJ pool 9/11"

"JobScheduler FJ pool 9/11":
  waiting to lock monitor 0x0000600004efc1a0 (object 0x0000000788e5bb80, a java.util.HashMap),
  which is held by "JobScheduler FJ pool 12/11"

Java stack information for the threads listed above:
===================================================
"AWT-EventQueue-0":
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.acquire(NonBlockingReadActionImpl.java:381)
	- waiting to lock <0x0000000788e5bb80> (a java.util.HashMap)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.<init>(NonBlockingReadActionImpl.java:268)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.submit(NonBlockingReadActionImpl.java:234)
	at com.intellij.openapi.editor.EditorMouseHoverPopupManager.showInfoTooltip(EditorMouseHoverPopupManager.java:423)
	at com.intellij.openapi.editor.EditorMouseHoverPopupManager.handleMouseMoved(EditorMouseHoverPopupManager.java:134)
	at com.intellij.openapi.editor.EditorMouseHoverPopupManager$MyEditorMouseMotionEventListener.mouseMoved(EditorMouseHoverPopupManager.java:555)
	at com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$3.lambda$mouseMoved$0(EditorEventMulticasterImpl.java:96)
	at com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$3$$Lambda$6045/0x000000080288e518.accept(Unknown Source)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.kt:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:50)
	at com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$3.mouseMoved(EditorEventMulticasterImpl.java:96)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseMotionListener.mouseMoved(EditorImpl.java:4626)
	at java.awt.Component.processMouseMotionEvent(java.desktop/Component.java:6702)
	at javax.swing.JComponent.processMouseMotionEvent(java.desktop/JComponent.java:3403)
	at java.awt.Component.processEvent(java.desktop/Component.java:6426)
	at java.awt.Container.processEvent(java.desktop/Container.java:2266)
	at java.awt.Component.dispatchEventImpl(java.desktop/Component.java:5027)
	at java.awt.Container.dispatchEventImpl(java.desktop/Container.java:2324)
	at java.awt.Component.dispatchEvent(java.desktop/Component.java:4855)
	at java.awt.LightweightDispatcher.retargetMouseEvent(java.desktop/Container.java:4969)
	at java.awt.LightweightDispatcher.processMouseEvent(java.desktop/Container.java:4596)
	at java.awt.LightweightDispatcher.dispatchEvent(java.desktop/Container.java:4524)
	at java.awt.Container.dispatchEventImpl(java.desktop/Container.java:2310)
	at java.awt.Window.dispatchEventImpl(java.desktop/Window.java:2809)
	at java.awt.Component.dispatchEvent(java.desktop/Component.java:4855)
	at java.awt.EventQueue.dispatchEventImpl(java.desktop/EventQueue.java:794)
	at java.awt.EventQueue$3.run(java.desktop/EventQueue.java:739)
	at java.awt.EventQueue$3.run(java.desktop/EventQueue.java:733)
	at java.security.AccessController.executePrivileged(java.base@17.0.8.1/AccessController.java:776)
	at java.security.AccessController.doPrivileged(java.base@17.0.8.1/AccessController.java:399)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@17.0.8.1/ProtectionDomain.java:86)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@17.0.8.1/ProtectionDomain.java:97)
	at java.awt.EventQueue$4.run(java.desktop/EventQueue.java:766)
	at java.awt.EventQueue$4.run(java.desktop/EventQueue.java:764)
	at java.security.AccessController.executePrivileged(java.base@17.0.8.1/AccessController.java:776)
	at java.security.AccessController.doPrivileged(java.base@17.0.8.1/AccessController.java:399)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@17.0.8.1/ProtectionDomain.java:86)
	at java.awt.EventQueue.dispatchEvent(java.desktop/EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:687)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:634)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:579)
	at com.intellij.ide.IdeEventQueue$$Lambda$1353/0x0000000800d07860.run(Unknown Source)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:579)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:71)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:353)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:353)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1006)
	at com.intellij.ide.IdeEventQueueKt$$Lambda$714/0x000000080075a8e8.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1006)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$$Lambda$711/0x0000000800756980.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:851)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:390)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop/EventDispatchThread.java:207)
	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop/EventDispatchThread.java:128)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop/EventDispatchThread.java:117)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop/EventDispatchThread.java:113)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop/EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.run(java.desktop/EventDispatchThread.java:92)
"JobScheduler FJ pool 12/11":
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$handleRequest$3(RemoteEndpoint.java:299)
	- waiting to lock <0x000000079ecd8c60> (a java.util.LinkedHashMap)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint$$Lambda$4179/0x0000000801fa0bd0.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(java.base@17.0.8.1/CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17.0.8.1/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.cancel(java.base@17.0.8.1/CompletableFuture.java:2480)
	at com.redhat.devtools.intellij.lsp4ij.client.LSPCompletableFuture.cancel(LSPCompletableFuture.java:157)
	at com.redhat.devtools.intellij.lsp4ij.client.LSPCompletableFuture.lambda$bind$0(LSPCompletableFuture.java:84)
	at com.redhat.devtools.intellij.lsp4ij.client.LSPCompletableFuture$$Lambda$4515/0x0000000802141838.accept(Unknown Source)
	at org.jetbrains.concurrency.AsyncPromise.onError$lambda$4(AsyncPromise.kt:96)
	at org.jetbrains.concurrency.AsyncPromise$$Lambda$1189/0x0000000800bc9ce0.accept(Unknown Source)
	at org.jetbrains.concurrency.AsyncPromise$whenComplete$1.invoke(AsyncPromise.kt:114)
	at org.jetbrains.concurrency.AsyncPromise$whenComplete$1.invoke(AsyncPromise.kt:112)
	at org.jetbrains.concurrency.AsyncPromise.whenComplete$lambda$6(AsyncPromise.kt:112)
	at org.jetbrains.concurrency.AsyncPromise$$Lambda$1190/0x0000000800bca490.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniHandle(java.base@17.0.8.1/CompletableFuture.java:934)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(java.base@17.0.8.1/CompletableFuture.java:911)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17.0.8.1/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.completeExceptionally(java.base@17.0.8.1/CompletableFuture.java:2162)
	at org.jetbrains.concurrency.AsyncPromise.cancel(AsyncPromise.kt:70)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.cancel(NonBlockingReadActionImpl.java:328)
	at org.jetbrains.concurrency.AsyncPromise.cancel(AsyncPromise.kt:73)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.cancel(NonBlockingReadActionImpl.java:636)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.submitOrScheduleCoalesced(NonBlockingReadActionImpl.java:425)
	- locked <0x0000000788e5bb80> (a java.util.HashMap)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.submit(NonBlockingReadActionImpl.java:239)
	at com.redhat.devtools.intellij.lsp4ij.client.LSPCompletableFuture.nonBlockingReadActionPromise(LSPCompletableFuture.java:146)
	at com.redhat.devtools.intellij.lsp4ij.client.LSPCompletableFuture.<init>(LSPCompletableFuture.java:69)
	at com.redhat.devtools.intellij.lsp4ij.client.IndexAwareLanguageClient.runAsBackground(IndexAwareLanguageClient.java:54)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.getJavaCodelens(QuteLanguageClient.java:199)
	at jdk.internal.reflect.GeneratedMethodAccessor220.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.8.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.8.1/Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint$$Lambda$3988/0x0000000801eb65b8.apply(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at com.redhat.devtools.intellij.lsp4ij.LanguageServerWrapper.lambda$start$1(LanguageServerWrapper.java:334)
	at com.redhat.devtools.intellij.lsp4ij.LanguageServerWrapper$$Lambda$4008/0x0000000801ec7d40.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(java.base@17.0.8.1/CompletableFuture.java:1804)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(java.base@17.0.8.1/CompletableFuture.java:1796)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@17.0.8.1/ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@17.0.8.1/ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(java.base@17.0.8.1/ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@17.0.8.1/ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@17.0.8.1/ForkJoinWorkerThread.java:165)
"JobScheduler FJ pool 9/11":
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.release(NonBlockingReadActionImpl.java:388)
	- waiting to lock <0x0000000788e5bb80> (a java.util.HashMap)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.cleanup(NonBlockingReadActionImpl.java:366)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.cleanupIfNeeded(NonBlockingReadActionImpl.java:353)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.cancel(NonBlockingReadActionImpl.java:329)
	at com.redhat.devtools.intellij.lsp4ij.client.LSPCompletableFuture.cancel(LSPCompletableFuture.java:154)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleCancellation(RemoteEndpoint.java:242)
	- locked <0x000000079ecd8c60> (a java.util.LinkedHashMap)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:217)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at com.redhat.devtools.intellij.lsp4ij.LanguageServerWrapper.lambda$start$1(LanguageServerWrapper.java:334)
	at com.redhat.devtools.intellij.lsp4ij.LanguageServerWrapper$$Lambda$4008/0x0000000801ec7d40.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(java.base@17.0.8.1/CompletableFuture.java:1804)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(java.base@17.0.8.1/CompletableFuture.java:1796)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@17.0.8.1/ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@17.0.8.1/ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(java.base@17.0.8.1/ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@17.0.8.1/ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@17.0.8.1/ForkJoinWorkerThread.java:165)

Found 1 deadlock.
```

### PR DESCRIPTION
**Pull request by angelozerr**
fix: Deadlock with IDEA EAP 2023-3 EAP

Fixes #1192

### CODE REVIEW

**Comment by fbricon** [comment]
seems to work. No deadlock in 15 min

**Comment by angelozerr** [comment]
> seems to work. No deadlock in 15 min

Thanks for your feedback.

I indeed fix the freeze problem which comes from cancel of codelens which is done every time. So it doesn't freeze but for the moment codelensare not displayed because of cancel which is done every time, why?

My PR fixes all problem that I have encountered with EAP:

 * freeze when cancel is done (fixed)
 * telemetry which throw an exception when language server is created (I try / catch teh call of telemetry)
 * don't use StringUtils from commons which will be removed

Now I need to understand why codelens are canceled every time.

**Comment by fbricon** [comment]
we need to understand why telemetry fails

**Comment by angelozerr** [comment]
I close this since I have create several push to fix main problem with EAP

**Pull request closed without merging**
