### PR TITLE
Add missing default cases in switch statements

### PR DESCRIPTION
**Pull request by paser4se**
Signed-off-by: PASER4SE <aarahman@ncsu.edu>

As mentioned in https://github.com/redhat-developer/intellij-quarkus/pull/183 added sign-off header ... will replace the existing two pull requests

### CODE REVIEW

**Comment by paser4se** [comment]
According to CWE, not having a default case for switch statements in code is a security weakness. See https://cwe.mitre.org/data/definitions/478.html

**Comment by paser4se** [comment]
> As indicated in the README, the whole intellij-community folder is an exact substract of the intellij-community open source project so we should not modify them. So can you remove this change from your PR

Which one ... HTTP or missing default?

**Comment by jeffmaury** [comment]
Yes the http -> https switch as my comment was about `intellij-community` sub folder

**Comment by paser4se** [comment]
Fixed the `http` issue.

**Pull request merged**
