### PR TITLE
feat: improve extension (de)selection in Quarkus wizard

### PR DESCRIPTION
**Pull request by fbricon**
- (de)select extension on double-click in extensions treeview
- deselect extension on double-click in selected extensions list
- deselect selection of extension on DELETE or BACKSPACE keypress in selected extensions list

Jul-01-2023 22-41-24

### CODE REVIEW

**Comment by fbricon** [comment]
Updated commit to handle cases when the treeview is filtered, and selected extensions are not visible in the treeview. Removing them (double-click or delete) now works as expected.

**Review by adietish — APPROVED** [review]
Works nicely for me, LGTM.
Extracted classes, methods to improve code readability a bit.

**Comment by adietish** [comment]
@fbricon added a commit on top for a bit of cleanup. Please have a look if you agree.

**Comment by fbricon** [comment]
@adietish thanks

**Pull request merged**
