### PR TITLE
fix: signature resolution of method parameters must ignore annotations (#935)

### LINKED ISSUE #935: Qute signature resolution of method parameters must ignore annotations
project is https://github.com/ia3andy/quarkus-blast
plugin version is 1.20.0

image

In this case it's not an error, the last parameter is a `@RestForm` so not part of the uri.

@fromage do you have some doc about this? It's true that it's a bit confusing at first.

### PR DESCRIPTION
**Pull request by angelozerr**
fix: resolve signature of method parameters must ignore annotations (#935)

Fixes #935

### CODE REVIEW

**Comment by fbricon** [comment]
I don't understand the relationship between this commit message and the actual change

**Comment by angelozerr** [comment]
To test this PR, open https://github.com/ia3andy/quarkus-blast/blob/f663d8ab204d6470d1be520fc0b699feaeff1f76/src/main/resources/templates/QuarkusBlast/index.html#L23

You should see no error and if you hover the play method you should see

image

**Review by fbricon — APPROVED** [review]
Works for me

**Comment by angelozerr** [comment]
Test woks now! I merge the  PR.

**Pull request merged**
