### PR TITLE
feat: support codelens for Quarkus 3/Jakarta REST endpoints

### LINKED ISSUE #795: Codelens should not be indented
**Steps:**
1. ASSERT: have a quarkus project with a REST resource class where a method is annotated with a path.
ex.
```
@RestClient
@Path("/extension")
public class ExtensionsResource {

    @Inject
    ExtensionsService extensionsService;

    @GET
    @Path("/id/{id}")
    public Set<Extension> id(@PathParam String id) {
        return extensionsService.getById(id);
    }
}
```
1. EXEC: open the class in an editor

**Result:**
The url for the annotated method is displayed. The url is indented on the left though
image

**Excpected result:**
The url should not be indented, should ideally be left aligned with the `@Path` annotation

### PR DESCRIPTION
**Pull request by fbricon**
- feat: support codelens for Quarkus 3/Jakarta REST endpoints
- fix: align URL codelens with annotation (fixes #795)

### CODE REVIEW

**Comment by angelozerr** [comment]
The PR works like a charm, the fix of codelens URL is better but there are some usecase which doesn't work like:

image

or:

image

But it is not a commons usecase. Commons usecases works great. We could improve again those CodeLens in a sperate PR.

I think we should see how to IJ manages `Usage inlay hint`.

**Comment by fbricon** [comment]
> The PR works like a charm, the fix of codelens URL is better but there are some usecase which doesn't work like:
> 
> image
> 
> or:
> 
> image
> 
> But it is not a commons usecase. Commons usecases works great. We could improve again those CodeLens in a sperate PR.
> 
> I think we should see how to IJ manages `Usage inlay hint`.

This is already reported as #796. I'm working on a fix but it's a bit tricky.

**Comment by angelozerr** [comment]
My bad CI build failed because tests https://github.com/redhat-developer/intellij-quarkus/actions/runs/4821889147/jobs/8588384324#step:5:79

@fbricon if you have time to fix it it would be really nice. Thanks.

**Comment by fbricon** [comment]
@angelozerr sorry, the fix is here: https://github.com/redhat-developer/intellij-quarkus/pull/826

BTW, the commits of this PR were separated on purpose, they were not supposed to be squashed.

**Pull request merged**
