### PR TITLE
fix: prevent reporting offsets outside editor document (#764)

### LINKED ISSUE #764: java.lang.IndexOutOfBoundsException when trying to "insert @RestClient"
**Steps:**
1. EXEC: have git@github.com:adietish/code-with-quarkus.git cloned and imported into IJ
2. EXEC: open `ExtenstionsResource.java` in an editor
3. EXEC: put cursor into `extensionsService` and activate the suggestions (press Alt + Return)
4. ASSERT: "Insert @RestClient" is suggested
image
6. EXEC: select it

**Result:**
"@RestClient" is not inserted, fatal IDE error is displayed with the following stacktrace:
```
java.lang.IndexOutOfBoundsException: Wrong line: 22. Available lines count: 21
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:200)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:181)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:1027)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LSPIJUtils.toOffset(LSPIJUtils.java:120)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LSPIJUtils.applyWorkspaceEdit(LSPIJUtils.java:219)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LSPIJUtils.applyWorkspaceEdit(LSPIJUtils.java:157)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.operations.codeactions.LSPCodeActionIntentionAction.apply(LSPCodeActionIntentionAction.java:96)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.operations.codeactions.LSPCodeActionIntentionAction.invoke(LSPCodeActionIntentionAction.java:84)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.lambda$invoke$0(IntentionActionWithTextCaching.java:223)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:194)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:223)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$8(ShowIntentionActionsHandler.java:273)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:946)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:972)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:86)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:273)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$7(ShowIntentionActionsHandler.java:250)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:249)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.chooseActionAndInvoke(IntentionListStep.java:137)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$0(IntentionListStep.java:129)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$17(AbstractPopup.java:1618)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:172)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.kt:187)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.kt:153)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:168)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:162)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1616)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:165)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:391)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:264)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:252)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:273)
	at com.intellij.ui.popup.list.ListPopupImpl.disposePopup(ListPopupImpl.java:485)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:512)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:479)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:426)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:281)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:400)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:372)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:115)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:157)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:107)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:546)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### PR DESCRIPTION
**Pull request by adietish**
fixes #764

### CODE REVIEW

**Comment by adietish** [comment]
according to @mickaelistria the error seen here points to a problem in the server. According to @jeffmaury this isn't the case because lsp in the context of IJ always sends the full document and thus has to handle cases that never occurr in Eclipse. In his opinion this fix is thus legit.

**Comment by mickaelistria** [comment]
> according to @mickaelistria the error seen here points to a problem in the server.

It's not really my opinion, it's the specification that says that the range of a TextEdit that is supposed to be a valid range in the originating document. An invalid range is... not valid.

**Comment by jeffmaury** [comment]
> > according to @mickaelistria the error seen here points to a problem in the server.
> 
> It's not really my opinion, it's the specification that says that the range of a TextEdit that is supposed to be a valid range in the originating document. An invalid range is... not valid.

That means we should update the code actions we generate to return a range computed on the original document and not on the new document generated

**Comment by angelozerr** [comment]
When I see the original issue it is about code action which generates several textedit, right?

If it that I wonder if the  ode action with one textedit is working?

@mickaelistria I m pretty sure the problem comes from ij lsp and not from language server since we consume it in vscode and lsp4e and it works good

**Comment by mickaelistria** [comment]
Here is a piece of the conversation @adietish and I had over direct messages.

```json
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///Users/andredietisheim/git/code-with-quarkus/src/main/java/org/acme/rest/client/ExtensionsResource.java","languageId":"qute","version":1,"text":"package org.acme.rest.client;\n\nimport org.eclipse.microprofile.rest.client.inject.RestClient;\nimport org.eclipse.microprofile.rest.client.inject.RestClient;\nimport org.jboss.resteasy.annotations.jaxrs.PathParam;\n\nimport javax.inject.Inject;\nimport javax.ws.rs.GET;\nimport javax.ws.rs.Path;\nimport java.util.Set;\n\n@Path(\"/extension\")\npublic class ExtensionsResource {\n\n    @Inject\n    ExtensionsService extensionsService;\n\n    @GET\n    @Path(\"/id/{id}\")\n    public Set\u003cExtension\u003e id(@PathParam String id) {\n        return extensionsService.getById(id);\n    }\n}"}}}
```
Is a 22-lines document
and then
```
Range [
  start = Position [
    line = 0
    character = 0
  ]
  end = Position [
    line = 24
    character = 1
  ]
]
```
line 24 obviously doesn't exist at all, so the range doesn't describe "The range of the text document to be manipulated" as defined in https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit .

**Comment by angelozerr** [comment]
> According to @jeffmaury this isn't the case because lsp in the context of IJ always sends the full document and thus has to handle cases that never occurr in Eclipse. 

For information, IJ doesn't send the full document if language server has the capability to manage document synck kind  with incremental (LSP TextDocumentSyncKind.Incremental)mean. As MicroProfile LS and Qute LS can manage incremental sync. For performance it is important to have incremental support to avoid sending the full document which can be expansive with large document.

**Pull request closed without merging**
