### PR TITLE
Use Quarkus Tools like for vscode and eclipse

### PR DESCRIPTION
**Pull request by maxandersen**

### CODE REVIEW

**Comment by maxandersen** [comment]
we now require signoff on PR's ? that’s a shame - so can't use github ui :/ 

yeah, I think Quarkus Tools is a nice way of ensuring consistency of naming and give it a name that is possible to refer to without mixing Quarkus itself up with the tools for Quarkus.

**Comment by jeffmaury** [comment]
Yes that's a @richardfontana requirement.
But he VSCcode extension is named Quarkus even if the title is `Quarkus Tools for Visual Studio Code`

image

**Comment by maxandersen** [comment]
ah sure - i'm just talking about this main page and how its presented on intellij marketplace where I assume this readme eventually will show up too ?

**Comment by jeffmaury** [comment]
No JetBrains marketplace is not as good as VSCode one: the info showed there is embedded in the plugin.xml thus we need duplication there.

**Comment by jeffmaury** [comment]
Replaced by #37

**Pull request closed without merging**
