### PR TITLE
Add code to run UI tests on os x to the '.github/workflows/ci.yml'

### LINKED ISSUE #293: Add code to run UI tests on os x to the ".github/workflows/ci.yml"

### PR DESCRIPTION
**Pull request by zcervink**
Fixes #293

Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>

Please review @jeffmaury

### CODE REVIEW

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Job is running for several hours so there are some issues.
- add -s flag to curl for better log readability
- need to understand why the IDE is never really started (no listening on port 8082)

**Comment by zcervink** [comment]
@jeffmaury I have tried to add the **-s** flag to the curl cmd, now it seems that the curl does not give any output at all. I have tried manually on OS X and linux, the -s flag really makes the curl to give no output. I have discussed the "github action issue" with @jrichter1 @jkopriva @odockal. I have informed all of them that I have tried several times to resolve this issue - I have tried to replace the current code with one-line cmd now included in the README file, I have tried to delete the build steps in the workflow to investigate the behavior (build of the plugin and run of the JUNIT tests) - this step do not make any changes.

**Comment by jeffmaury** [comment]
That was the key to adding the -s: prevent the log to be polluted by curl output and rely only on the curl exit code

**Comment by zcervink** [comment]
@jeffmaury Now I understand. But it gave us nothing except the information that the process has been canceled. I see the "_Unable to create basic Accelerated OpenGL renderer_" line but I think it has nothing to do with our issue. The IntelliJ has not started and it is not accessible on the specific port.

**Pull request closed without merging**
