### PR TITLE
refactor: Code Hygiene

### PR DESCRIPTION
**Pull request by gurpal2000**
- Removed unused imports
- Removed redundant typecast

### CODE REVIEW

**Review by jeffmaury — CHANGES_REQUESTED** [review]
DCO is required for contributors

**Comment by gurpal2000** [comment]
@jeffmaury thanks i wasn't sure on the process. My first PR on any RH project!

**Comment by gurpal2000** [comment]
@jeffmaury Thanks, how do I get a DCO?

**Comment by jeffmaury** [comment]
You need to commit with the `-s` flag.

**Comment by jeffmaury** [comment]
You need to either:
- rebase all commits as a single one with DCO header
- add DCO header to each commit

**Comment by gurpal2000** [comment]
Will close and create a new PR

**Pull request closed without merging**
