### PR TITLE
Add integration tests for Linux

### LINKED ISSUE #254: Add the integration tests execution in the main Github Actions (not a separate github action, but a modif to the CI.yml)
Add the integration tests execution in the main Github Actions so that we run the integration tests as well (not a separate github action, but a modif to the CI.yml)

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #254

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by zcervink** [comment]
@jeffmaury I have investigated why the UI tests are failing - the UI of IntelliJ Idea has changed over time and the tests are being run with an old version of IntelliJ. Solution for now is to extend the gradlew cmd and add there parametr to use the 2020.1 version of IntelliJ:

 **./gradlew runIdeForUiTests -PideaVersion=2020.1 &**

The newest version of IntelliJ (2020.2) has also some changes in UI and the tests are failing due to them, I am currently investigating the issues/UI changes and I am planning to update the tests to support the newest version of IntelliJ.

**Comment by zcervink** [comment]
@jeffmaury @jkopriva @jrichter1 I was investigating the linux build - it has failed but it looks like the IDE started, the test runs and when the maven build started, the NoSuchElementException appears. It looks like it is an issue in my test, I have created issue for that - https://github.com/redhat-developer/intellij-quarkus/issues/318

Could anyone extend the issue and add there the full stacktrace please? It is probably included in the following file but I do not know how to access it (I have gotten the link from the failed linux build - see above the checks):

`file:///home/runner/work/intellij-quarkus/intellij-quarkus/build/reports/tests/integrationTest/index.html`

**Note:** Then there is a second exception - WaitForConditionTimeoutException - we do not need to investigate this, it is in the Junit AfterAll after the test has failed due to the first exception.

**Comment by zcervink** [comment]
@jeffmaury I see that your PR (after several commits) finally starts the IDE, leaves the loop and starts the tests (well the tests fails but thats another story - probably this issue https://github.com/redhat-developer/intellij-quarkus/issues/320)

**Comment by jeffmaury** [comment]
@zcervink I'm lost with so many PRs about the almost same issue. What should I do to make my PR pass the ITs ?

**Comment by zcervink** [comment]
@jeffmaury Congratulations, it looks like your part of the work is done (at least for now). After some investigation (testing on Linux, Windows, Mac) and discussion with @jrichter1 I have found issue in my UI tests:

1) The tests pass on OS X
2) Due to some differences between **OS X** and **Linux+WIN** the tests do not pass on **Linux+WIN**, I am working on fixes
- **ISSUE NO. 1**: On OS X - opened projet in IntelliJ Idea can be closed by clicking on the **X** button on the left top corner of the window. On **Linux+Win** this action closes the IDE completely (which causes the first test to fail and following tests will not even start)
- **ISSUE NO. 2**: On OS X there are native menus, on **Linux+WIN** not - working on support all platforms.

**Comment by zcervink** [comment]
@jeffmaury I have managed to create a PR to fix closing the project on Linux+Win - https://github.com/redhat-developer/intellij-quarkus/pull/330 With @jrichter1 we think this is small but really important fix (without this fix we are not able to finish neither the github actions/workflows nor the other PRs for adding more UI tests). After this fix I believe the UI tests in this PR passes.

**Comment by jeffmaury** [comment]
@zcervink so should I merge this PR first ?

**Pull request closed without merging**
