### PR TITLE
#68: Lost color completion in application.properties

### PR DESCRIPTION
**Pull request by koentsje**
Signed-off-by: Koen Aers <koen.aers@gmail.com>

### CODE REVIEW

**Comment by koentsje** [comment]
@jeffmaury do i have to do something more to have this merged?

**Comment by jeffmaury** [comment]
Yes me to review it and not use it has the Fixes # comment

**Comment by koentsje** [comment]
So the commit comment should rather say:

    Lost color completion in application.properties

    Fixex #68 
    
    Signed-off-by: Koen Aers <koen.aers@gmail.com>

Is this how you want it? Shall I close this and open a new one?

**Comment by jeffmaury** [comment]
> 
> 
> So the commit comment should rather say:
> 
> ```
> Lost color completion in application.properties
> 
> Fixes #68 
> 
> Signed-off-by: Koen Aers <koen.aers@gmail.com>
> ```
> 
> Is this how you want it? Shall I close this and open a new one?

No you just need to modify the commit message and do a forced push

**Pull request merged**
