### PR TITLE
Make the plugin build against version 2020.1

### LINKED ISSUE #83: Make the plugin build against version 2020.1
The plugin currently does not compile against the most recent versions of Idea
- org.jetbrains.intellij plugin version 0.4.19
- Idea version IC-2020.1
This is because of removed APIs

### PR DESCRIPTION
**Pull request by koentsje**
Fixes #83

Signed-off-by: Koen Aers <koen.aers@gmail.com>

### CODE REVIEW

**Comment by koentsje** [comment]
so I just leave the version to be 2019.1 and include the other changes in the commit?

**Comment by jeffmaury** [comment]
It will be implemented by https://github.com/redhat-developer/intellij-quarkus/pull/86
So if you rebase your PR once it got merged, then you will have the feedback on every supported IJ version

**Comment by koentsje** [comment]
OK cool, do you have any timing for this? Also, what I don't understand: how can you figure out problems with building against e.g. 2020.1 without changing this version in the gradle propertties? Is there a particular way to run the development environment for this? Or do I completely miss something?

**Comment by jeffmaury** [comment]
PR is now merged.

**Comment by jeffmaury** [comment]
Replaced by #94 

Closing as this one does not properly initialize new projects as full Gradle Java projects

**Pull request closed without merging**
