### PR TITLE
Update Quarkus Runtime to 1.4.2.Final (#71)

### PR DESCRIPTION
**Pull request by zcervink**
Update Quarkus Runtime to 1.4.2.Final (#71)

Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>
Tested on localhost.

Please review @jeffmaury 

**Displayed value:**
81204851-224f2780-8fca-11ea-91b7-8591bc84e59f

**Download works:**
Snímek obrazovky 2020-05-06 v 18 56 29

### CODE REVIEW

**Comment by zcervink** [comment]
testPR

**Comment by jeffmaury** [comment]
@zcervink PR validation is performed by GitHub Actions and Travis (to be removed). So testPR (Jenkins specific) has no effect. You can rerun Github Actions or Travis build using the details link

**Comment by zcervink** [comment]
@jeffmaury maybe we do not need to rerun after all. What is your opinion on this PR and the validation tests/checks? The failed tests has nothing to do with my changes in this PR, the tests are failing the same way on my localhost on both master and this_pr branches. I have only updated library version. Are you gonna merge? Or do you have some other requests?

**Comment by jeffmaury** [comment]
We don't support building against several versions of IJ so the only check that matters are the Java CI with Gradle and Travis. So this PR looks good

**Pull request merged**
