### PR TITLE
feat: improve LSP settings UI

### LINKED ISSUE #861: Improve settings UI
follows up on PR #849 

In the settings the UI could get a bit more pleasant when given a little love :)
* Horizontal rulers could group things a bit
* There's no border on the right side
* I'd use radio buttons instead of a combo given there are only 3 options (see jetbrains design guide: https://jetbrains.design/intellij/controls/radio_button/#when-to-use)
image
Compare it to other prefs pages in IJ:
image

### PR DESCRIPTION
**Pull request by fbricon**
Fixes #861 

- uses a PortField for the server port, with minimal validation 
- added titled border
- fixed left / right margins

However I spent an unreasonable amount of time trying to fix the wide margin between the title and the comment, but no dice. Still looks better than before (#861) so I gave up.

Screenshot 2023-06-22 at 19 11 18
Screenshot 2023-06-22 at 19 11 55

Signed-off-by: Fred Bricon <fbricon@gmail.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
Nice fix @fbricon !

@adietish do you think you could have time to review this PR?

**Comment by adietish** [comment]
image

**Comment by adietish** [comment]
@fbricon please review

**Review by adietish — APPROVED** [review]
LGTM.
Added a commit that removes the vertical gap.

**Comment by fbricon** [comment]
@adietish thanks!

**Pull request merged**
