### PR TITLE
fix: Fixed UI tests on Linux and Windows

### LINKED ISSUE #831: Fix integration Tests
As of today, last success of the integration tests jobs is 7 months old: https://github.com/redhat-developer/intellij-quarkus/actions/workflows/itests.yml?page=4&query=branch%3Amain+

Today, the integration tests don't even compile.

Either fix it or can it.

### PR DESCRIPTION
**Pull request by olkornii**
Fixes #831 for windows and linux.

### CODE REVIEW

**Comment by fbricon** [comment]
Can you explain why MacOS can't be enabled?

**Comment by fbricon** [comment]
can you update the GHA versions, to avoid the warnings seen in https://github.com/redhat-developer/intellij-quarkus/actions/runs/9775010131

**Comment by olkornii** [comment]
> Can you explain why MacOS can't be enabled?

I've already explained it during the call. I don't have a macOS machine, so it might take more time for me to investigate macOS specific issues. But due to changes in QE team I don't have this time.

**Comment by olkornii** [comment]
> can you update the GHA versions, to avoid the warnings seen in https://github.com/redhat-developer/intellij-quarkus/actions/runs/9775010131

I'll check it.

**Comment by fbricon** [comment]
> I've already explained it during the call. I don't have a macOS machine, so it might take more time for me to investigate macOS specific issues. But due to changes in QE team I don't have this time.

I get that, but I assume you saw build failures on Mac agents on GHA, that led you to disable those tests. I just want to know what failures were reported.

**Comment by olkornii** [comment]
> > I've already explained it during the call. I don't have a macOS machine, so it might take more time for me to investigate macOS specific issues. But due to changes in QE team I don't have this time.
> 
> I get that, but I assume you saw build failures on Mac agents on GHA, that led you to disable those tests. I just want to know what failures were reported.

I can't say what the problem is based only on GHA output. So I didn't report it.
There is a test run: https://github.com/olkornii/intellij-quarkus/actions/runs/9659680083/job/26644804801

**Comment by fbricon** [comment]
Ok, pasting the output here, since build outputs will be pruned eventually:

```
> Task :integrationTest

BasicTest STANDARD_ERROR
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/Users/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.2/26a4bf0a5c959ecd024f48fa6d3b53c4741fdb8e/ideaIC-2023.2/plugins/maven/lib/maven36-server.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/Users/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.2/26a4bf0a5c959ecd024f48fa6d3b53c4741fdb8e/ideaIC-2023.2/lib/util-8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.jetbrains.idea.maven.server.Maven3WrapperSl4LoggerFactory]

BasicTest > createBuildQuarkusGradleTest() STANDARD_ERROR
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT30S) for condition function (Failed to find 'Button' by '//div[@text='Background']' in 30s) 
    	at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
    	at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
    	at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
    	at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
    	at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
    	at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
    	at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
    	at org.jboss.tools.intellij.quarkus.tests.BasicTest.minimizeProjectImportPopupIfItAppears(BasicTest.java:143)
    	at org.jboss.tools.intellij.quarkus.tests.BasicTest.createQuarkusProject(BasicTest.java:132)
    	at org.jboss.tools.intellij.quarkus.tests.BasicTest.createBuildQuarkusGradleTest(BasicTest.java:79)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
    	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
    	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
    	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
    	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
    	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
    	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
    	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
    	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
    	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
    	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
    	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
    	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
    	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
    	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
    	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
    	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
    	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:119)
    	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:94)
    	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:89)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
    	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
    	at jdk.proxy2/jdk.proxy2.$Proxy5.stop(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
    	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
    	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
    	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
    	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
    	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
org.jboss.tools.intellij.quarkus.tests.BasicTest

  Test createBuildQuarkusGradleTest() FAILED (8m 8s)

  com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT2S) for condition function (Failed to find 'Tool Window Pane' by 'ToolWindowPane type' in 2s)
      at org.jboss.tools.intellij.quarkus.tests.BasicTest.buildGradleProject(BasicTest.java:155)


BasicTest > createBuildQuarkusGradleTest() FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT2S) for condition function (Failed to find 'Tool Window Pane' by 'ToolWindowPane type' in 2s) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:34)
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:28)
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at org.jboss.tools.intellij.quarkus.tests.BasicTest.buildGradleProject(BasicTest.java:155)
        at org.jboss.tools.intellij.quarkus.tests.BasicTest.createBuildQuarkusGradleTest(BasicTest.java:87)

Gradle Test Executor 2 finished executing tests.

> Task :integrationTest
  Test createBuildQuarkusMavenTest() FAILED (38.8s)

  com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'Welcome To IntelliJ IDEA Dialog' by 'FlatWelcomeFrame type' in 10s)
      at org.jboss.tools.intellij.quarkus.tests.BasicTest.createQuarkusProject(BasicTest.java:102)


BasicTest > createBuildQuarkusMavenTest() FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'Welcome To IntelliJ IDEA Dialog' by 'FlatWelcomeFrame type' in 10s) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
        at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:34)
        at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
        at org.jboss.tools.intellij.quarkus.tests.BasicTest.createQuarkusProject(BasicTest.java:102)
        at org.jboss.tools.intellij.quarkus.tests.BasicTest.createBuildQuarkusMavenTest(BasicTest.java:68)


FAILURE: Executed 2 tests in 11m 11s (2 failed)
2 tests completed, 2 failed

Finished generating test XML results (1.971 secs) into: /Users/runner/work/intellij-quarkus/intellij-quarkus/build/test-results/integrationTest
Generating HTML test report...
Finished generating test html results (0.394 secs) into: /Users/runner/work/intellij-quarkus/intellij-quarkus/build/reports/tests/integrationTest
Invalidating in-memory cache of /Users/runner/work/intellij-quarkus/intellij-quarkus/.gradle/8.6/fileHashes/fileHashes.bin
Invalidating in-memory cache of /Users/runner/work/intellij-quarkus/intellij-quarkus/.gradle/8.6/fileHashes/resourceHashesCache.bin
Invalidating in-memory cache of /Users/runner/work/intellij-quarkus/intellij-quarkus/.gradle/8.6/executionHistory/executionHistory.bin
Invalidating in-memory cache of /Users/runner/work/intellij-quarkus/intellij-quarkus/.gradle/buildOutputCleanup/outputFiles.bin

> Task :integrationTest FAILED

0 problems were found storing the configuration cache.

See the complete report at file:///Users/runner/work/intellij-quarkus/intellij-quarkus/build/reports/configuration-cache/1hnj03q7mxqndrz7ar4knub18/3fxhriukfr62d3851dnzh4n8v/configuration-cache-report.html

FAILURE: Build failed with an exception.
```

**Comment by fbricon** [comment]
Thanks @olkornii!

**Comment by olkornii** [comment]
@fbricon 
Shouldn't we create an issue "Fix UI test on macOS"?

**Comment by fbricon** [comment]
@olkornii see #1350

**Pull request merged**
